packages:
  - 'apps/*'
  - 'next/*'
  - 'vue/*'
  - 'packages/*'
allowBuilds:
  esbuild: false
  sharp: true
  vue-demi: true
minimumReleaseAgeExclude:
  - '@playwright/test@1.62.0'
  - playwright-core@1.62.0
  - playwright@1.62.0
